### ISSUE TITLE
Error with Julia 0.6.4

### ISSUE THREAD

**Issue by songanz** [JuliaPOMDP/QMDP.jl#12]
`using POMDPs, POMDPModels, POMDPToolbox, QMDP
pomdp = TigerPOMDP()

solver = QMDPSolver() 
policy = solve(solver, pomdp)
belief_updater = updater(policy)`

I get some error: UndefVarError: QMDPSolver not defined. When using QMDP in Julia 0.6.4

**Comment by zsunberg** [comment]
Was this because of JuliaPOMDP/POMDPs.jl#210?
