### ISSUE TITLE
Why do we need QMDPBelief?

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/QMDP.jl#2]
Couldn't we just use DiscreteBelief and DiscreteUpdater without wrapping them in QMDPBelief?

**Comment by zsunberg** [comment]
Another reason to use DiscreteBelief is that, if someone wants to build a custom updater for a discrete problem, they would want to implement it for a DiscreteBelief rather than tie it to QMDP

**Comment by etotheipluspi** [comment]
Fixed with cb2638d2a386e91bd1e7fbca73c6043b790b046c
